Traceback (most recent call last):
  File "C:\Users\sashk\AppData\Local\Programs\Python\Python313\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\sashk\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\sashk\AppData\Local\Programs\Python\Python313\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sashk\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\sashk\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "C:\Users\sashk\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sashk\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
G = nx.read_edgelist("facebook_combined.txt", create_using=nx.Graph(), nodetype=int)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[5], line 1[0m
[1;32m----> 1[0m G [38;5;241m=[39m [43mnx[49m[38;5;241;43m.[39;49m[43mread_edgelist[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mfacebook_combined.txt[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mcreate_using[49m[38;5;241;43m=[39;49m[43mnx[49m[38;5;241;43m.[39;49m[43mGraph[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mnodetype[49m[38;5;241;43m=[39;49m[38;5;28;43mint[39;49m[43m)[49m

File [1;32m~\anaconda3\envs\mlgBook\lib\site-packages\decorator.py:232[0m, in [0;36mdecorate.<locals>.fun[1;34m(*args, **kw)[0m
[0;32m    230[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m kwsyntax:
[0;32m    231[0m     args, kw [38;5;241m=[39m fix(args, kw, sig)
[1;32m--> 232[0m [38;5;28;01mreturn[39;00m [43mcaller[49m[43m([49m[43mfunc[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43m([49m[43mextras[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43margs[49m[43m)[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkw[49m[43m)[49m

File [1;32m~\anaconda3\envs\mlgBook\lib\site-packages\networkx\utils\decorators.py:213[0m, in [0;36mopen_file.<locals>._open_file[1;34m(func_to_be_decorated, *args, **kwargs)[0m
[0;32m    211[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(path, [38;5;28mstr[39m):
[0;32m    212[0m     ext [38;5;241m=[39m splitext(path)[[38;5;241m1[39m]
[1;32m--> 213[0m     fobj [38;5;241m=[39m [43m_dispatch_dict[49m[43m[[49m[43mext[49m[43m][49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mmode[49m[43m)[49m
[0;32m    214[0m     close_fobj [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m    215[0m [38;5;28;01melif[39;00m [38;5;28mhasattr[39m(path, [38;5;124m"[39m[38;5;124mread[39m[38;5;124m"[39m):
[0;32m    216[0m     [38;5;66;03m# path is already a file-like object[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'facebook_combined.txt'

